name: Documentation

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build documentation
        run: cargo doc --verbose --no-deps --document-private-items

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v5
        with:
          name: rust-docs
          path: target/doc
